### ISSUE TITLE
name 'TimeSeriesNnet' is not defined

### ISSUE THREAD

**Issue by cidj** [hawk31/nnet-ts#3]
I used Anaconda with python 3.6 on a Macbook Pro.  After successfully installed nnet-ts, when I wrote an import line: "from nnet_ts import *", there was an error and it told me that name 'TimeSeriesNnet' is not defined. Please help!

Thanks

**Comment by cidj** [comment]
I used "pip install nnet-ts"

**Comment by josejimenezluna** [comment]
It's been a while since I last checked on this project. I will revisit this issue later today.

**Comment by flacle** [comment]
Hi @hawk31, following up on this issue, any idea as to the cause? I just stumbled upon it, can also try to have a look.

**Comment by flacle** [comment]
Info from here seems to help: https://stackoverflow.com/questions/12172791/changes-in-import-statement-python3 - adapting the import statement from:
`from TimeSeriesNnet import TimeSeriesNnet`
to
`from .TimeSeriesNnet import TimeSeriesNnet`
solves the issue on my machine.

**Comment by josejimenezluna** [comment]
I haven't had time to revise this project, but it needs some serious cleaning and updating.
